### Metadata

title: Artists Portfolio
url: ""
baseurl: ""
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Photography portfolio for Jekyll.
author:
  name: Michael Currin
  email:
  twitter:
social:
  name: Artists Portfolio
  links:
    - https://github.com/MichaelCurrin/artists-portfolio

### Build settings

timezone: Etc/UTC

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      text_width: true
      image: /uploads/1.jpg
  - scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - vendor/

### CloudCannon

_options:
  image:
    width: 2048
    height: 1365
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true
